name = "navigation-worker"
main = "worker.js"
compatibility_date = "2023-12-01"

# KV命名空间绑定 - 部署时会自动填充
# 运行 'npm run setup' 会自动创建KV命名空间并更新此配置
[[kv_namespaces]]
binding = "NAVIGATION_KV"
id = ""
preview_id = ""

# 环境变量
[vars]
ENVIRONMENT = "production" 