name = "navigation-worker"
main = "worker.js"
compatibility_date = "2023-12-01"

# KV命名空间绑定
[[kv_namespaces]]
binding = "NAVIGATION_KV"
id = "YOUR_KV_NAMESPACE_ID"
preview_id = "YOUR_PREVIEW_KV_NAMESPACE_ID"

# 环境变量
[vars]
ENVIRONMENT = "production" 